; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: llvm-as < %s | llvm-dis | llvm-as | llvm-dis | FileCheck %s

define i32 @test1(ptr %p) !my.md !my.md { foo: i8 3 } {
  %r = load i32, ptr %p, !my.md !0
  ret i32 %r
}

!0 = !{ i32 5, !my.other{ bar: i16 22 } }

; CHECK: define i32 @test1(ptr %p) !my.md !0
; CHECK:   %r = load i32, ptr %p, !my.md !1
;
; TODO: the 'distinct's shouldn't be there
;
; CHECK:      !0 = distinct !my.md{
; CHECK-NEXT:   foo: i8 3,
; CHECK-NEXT: }
; CHECK-NEXT: !1 = !{i32 5, !2}
; CHECK-NEXT: !2 = distinct !my.other{
; CHECK-NEXT:   bar: i16 22,
; CHECK-NEXT: }
