; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -S -convergence-control-heuristic | FileCheck %s -check-prefix=CHECK

define void @basic() {
; CHECK-LABEL: @basic(
; CHECK-NEXT:    [[TMP1:%.*]] = call token @llvm.experimental.convergence.anchor()
; CHECK-NEXT:    call void asm sideeffect "dummy", ""() #1 [ "convergencectrl"(token [[TMP1]]) ]
; CHECK-NEXT:    ret void
;
  call void asm sideeffect "dummy", ""() convergent
  ret void
}
